//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MNepalAPI.COMMON {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CommonInterfaceSoap", Namespace="http://www.nibl.com.np/")]
    public partial class CommonInterface : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private HeaderInfo headerInfoValueField;
        
        private System.Threading.SendOrPostCallback SubmitRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CommonInterface() {
            this.Url = global::MNepalAPI.Properties.Settings.Default.MNepalAPI_COMMON_CommonInterface;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public HeaderInfo HeaderInfoValue {
            get {
                return this.headerInfoValueField;
            }
            set {
                this.headerInfoValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SubmitRequestCompletedEventHandler SubmitRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderInfoValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nibl.com.np/SubmitRequest", RequestNamespace="http://www.nibl.com.np/", ResponseNamespace="http://www.nibl.com.np/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseData SubmitRequest(string serviceId, string serviceCode, RequestData input) {
            object[] results = this.Invoke("SubmitRequest", new object[] {
                        serviceId,
                        serviceCode,
                        input});
            return ((ResponseData)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitRequestAsync(string serviceId, string serviceCode, RequestData input) {
            this.SubmitRequestAsync(serviceId, serviceCode, input, null);
        }
        
        /// <remarks/>
        public void SubmitRequestAsync(string serviceId, string serviceCode, RequestData input, object userState) {
            if ((this.SubmitRequestOperationCompleted == null)) {
                this.SubmitRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitRequestOperationCompleted);
            }
            this.InvokeAsync("SubmitRequest", new object[] {
                        serviceId,
                        serviceCode,
                        input}, this.SubmitRequestOperationCompleted, userState);
        }
        
        private void OnSubmitRequestOperationCompleted(object arg) {
            if ((this.SubmitRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitRequestCompleted(this, new SubmitRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nibl.com.np/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.nibl.com.np/", IsNullable=false)]
    public partial class HeaderInfo : System.Web.Services.Protocols.SoapHeader {
        
        private string h1Field;
        
        private string h2Field;
        
        private string h3Field;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string H1 {
            get {
                return this.h1Field;
            }
            set {
                this.h1Field = value;
            }
        }
        
        /// <remarks/>
        public string H2 {
            get {
                return this.h2Field;
            }
            set {
                this.h2Field = value;
            }
        }
        
        /// <remarks/>
        public string H3 {
            get {
                return this.h3Field;
            }
            set {
                this.h3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nibl.com.np/")]
    public partial class ResponseData {
        
        private string resultCodeField;
        
        private string resultDescriptionField;
        
        private string additionalDataField;
        
        /// <remarks/>
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalData {
            get {
                return this.additionalDataField;
            }
            set {
                this.additionalDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nibl.com.np/")]
    public partial class RequestData {
        
        private object field1Field;
        
        private object field2Field;
        
        private object field3Field;
        
        private object field4Field;
        
        private object field5Field;
        
        private object field6Field;
        
        private object field7Field;
        
        private object field8Field;
        
        private object field9Field;
        
        private object field10Field;
        
        private object field11Field;
        
        private object field12Field;
        
        private object field13Field;
        
        private object field14Field;
        
        private object field15Field;
        
        private object field16Field;
        
        private object field17Field;
        
        private object field18Field;
        
        private object field19Field;
        
        private object field20Field;
        
        /// <remarks/>
        public object Field1 {
            get {
                return this.field1Field;
            }
            set {
                this.field1Field = value;
            }
        }
        
        /// <remarks/>
        public object Field2 {
            get {
                return this.field2Field;
            }
            set {
                this.field2Field = value;
            }
        }
        
        /// <remarks/>
        public object Field3 {
            get {
                return this.field3Field;
            }
            set {
                this.field3Field = value;
            }
        }
        
        /// <remarks/>
        public object Field4 {
            get {
                return this.field4Field;
            }
            set {
                this.field4Field = value;
            }
        }
        
        /// <remarks/>
        public object Field5 {
            get {
                return this.field5Field;
            }
            set {
                this.field5Field = value;
            }
        }
        
        /// <remarks/>
        public object Field6 {
            get {
                return this.field6Field;
            }
            set {
                this.field6Field = value;
            }
        }
        
        /// <remarks/>
        public object Field7 {
            get {
                return this.field7Field;
            }
            set {
                this.field7Field = value;
            }
        }
        
        /// <remarks/>
        public object Field8 {
            get {
                return this.field8Field;
            }
            set {
                this.field8Field = value;
            }
        }
        
        /// <remarks/>
        public object Field9 {
            get {
                return this.field9Field;
            }
            set {
                this.field9Field = value;
            }
        }
        
        /// <remarks/>
        public object Field10 {
            get {
                return this.field10Field;
            }
            set {
                this.field10Field = value;
            }
        }
        
        /// <remarks/>
        public object Field11 {
            get {
                return this.field11Field;
            }
            set {
                this.field11Field = value;
            }
        }
        
        /// <remarks/>
        public object Field12 {
            get {
                return this.field12Field;
            }
            set {
                this.field12Field = value;
            }
        }
        
        /// <remarks/>
        public object Field13 {
            get {
                return this.field13Field;
            }
            set {
                this.field13Field = value;
            }
        }
        
        /// <remarks/>
        public object Field14 {
            get {
                return this.field14Field;
            }
            set {
                this.field14Field = value;
            }
        }
        
        /// <remarks/>
        public object Field15 {
            get {
                return this.field15Field;
            }
            set {
                this.field15Field = value;
            }
        }
        
        /// <remarks/>
        public object Field16 {
            get {
                return this.field16Field;
            }
            set {
                this.field16Field = value;
            }
        }
        
        /// <remarks/>
        public object Field17 {
            get {
                return this.field17Field;
            }
            set {
                this.field17Field = value;
            }
        }
        
        /// <remarks/>
        public object Field18 {
            get {
                return this.field18Field;
            }
            set {
                this.field18Field = value;
            }
        }
        
        /// <remarks/>
        public object Field19 {
            get {
                return this.field19Field;
            }
            set {
                this.field19Field = value;
            }
        }
        
        /// <remarks/>
        public object Field20 {
            get {
                return this.field20Field;
            }
            set {
                this.field20Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SubmitRequestCompletedEventHandler(object sender, SubmitRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591